input {
    beats {
        port => 5044
    }
}

filter {
}

output {
    stdout {
        codec => "json"
    }

    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "inside-view%{+YYYY.MM.dd+3}"
        user => "elastic"
        password => "elastic"
    }
}