input {
    beats {
        port => 5044
    }
}

filter {
}

output {
    stdout {
        codec => "json"
    }

    elasticsearch {
        hosts => "http://elasticsearch:9200"
        index => "inside-view_%{[fields][service]}-%{+YYYY.MM.DD}"
        user => "elastic"
        password => "elastic"
    }
}