version: '3.9'

volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local
  es-data:
    driver: local

networks:
  elk:
    driver: bridge

services:
  app:
    container_name: inside-view
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - redis
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/MiitInside
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'

  db:
    image: postgres:16.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MiitInside
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass TUlJVCBpbnNpZGV2aWV3
    volumes:
      - cache:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /minio --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/minio

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    networks:
      - elk

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    ports:
      - '5044:5044'
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
    depends_on:
      - elasticsearch
